"use client"

import { AppProvider } from '@/context/AppContext'
import './globals.css'
import Navigation from '@/components/Navigation'
import type { Metadata } from 'next'
import { SessionProvider } from 'next-auth/react'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProvider>
          <SessionProvider>
            <Navigation />
            {children}
          </SessionProvider>
        </AppProvider>
      </body>
    </html>
  )
}
